mesh_files:
  base:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/base.stl"

  shoulder:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/shoulder.stl"

  upper_arm:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/upperarm.stl"
      mesh_files:

  forearm:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/forearm.stl"

  wrist_1:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/wrist1.stl"
    visual_offset: -0.127

  wrist_2:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/wrist2.stl"
    visual_offset: -0.0997

  wrist_3:
    visual:
      mesh: "package://ur5e_description/ur5e_model/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur5e_description/ur5e_model/collision/wrist3.stl"
    visual_offset: -0.0989
